services:

    nginx:
            image: nginx:1.31.2-alpine
            container_name: aa-nginx
            restart: always
            ports:
                - 80:80
            volumes:
                - ./..:/var/www
                - ./sites-enabled:/etc/nginx/conf.d
                - ./run:/tmp/run
            networks:
                - default

    python:
        image: aa-python-3-14
        container_name: aa-python
        user: "1000:1000"
        restart: always
        working_dir: /app
        build:
            context: ./python-3-14
            dockerfile: Dockerfile
        environment:
            - GEMINI_API_KEY=${GEMINI_API_KEY}
            - HOME=/tmp
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - ./../back:/app
            - ./run:/tmp/run
            - ./.gemini:/tmp/.gemini
        command: sh -c "uvicorn app.main:app --uds /tmp/run/uvicorn.sock --reload 2>&1 | tee /app/uvicorn.log"

    db:
        image: postgres:18.4-alpine
        container_name: aa-db
        restart: always
        ports: 
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./../databases:/var/lib/postgresql